spring:
  datasource:
    url: jdbc:postgresql://localhost:${ORDER_POSTGRES_PORT:5433}/${ORDER_POSTGRES_DB:order_service_db}
    username: ${ORDER_POSTGRES_USER:order_service}
    password: ${ORDER_POSTGRES_PASSWORD:order_service_secret}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${ORDER_REDIS_PORT:6379}

  liquibase:
    contexts: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}
